---
- name: Update website
  ansible.builtin.command: |
    docker stop variation_website
    docker compose pull
    docker compose up -d

- name: Stop containers
  ansible.builtin.command: |
    docker-compose stop variation_website

- name: Pulling containers
  ansible.builtin.command: |
    docker-compose pull

- name: Start containers
  ansible.builtin.command: |
    docker-compose up -d