version: "3"

services:
  website:
    container_name: website
    build:
      context: ./website
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    ports:
      - 127.0.0.1:27017:27017
