version: "3"

services:
  website:
    image: ghcr.io/jonaskellerer/variation:latest
    container_name: variation_website
    build:
      context: ./website
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

  database:
    image: mongo:latest
    container_name: variation_database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    ports:
      - 27017:27017
