version: "3"

services:
  website:
    image: ghcr.io/jonaskellerer/variation:latest
    container_name: variation_website
    build:
      context: ./website
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
