version: "3"

services:
  website:
    image: ghcr.io/jonaskellerer/variation/website:{{ website_version}}
    ports:
      - 3000:3000

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
