---
- name: Stop containers
  ansible.builtin.command: |
    docker-compose down

- name: Pulling containers
  ansible.builtin.command: |
    docker-compose pull

- name: Start containers
  ansible.builtin.command: |
    docker-compose up -d
