name: Ansible on Server

on:
  workflow_call:
    inputs:
      ansible_file:
        description: 'Ansible file to run'
        required: true
        type: string


jobs:
  ansibleOnServer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H {{ secrets.SERVER_IP_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Run Ansible
        run: |
          ansible-playbook -i {{ secrets.SERVER_IP_ADDRESS }}, ${{ inputs.ansible_file }}