name: deployment

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ci-${{ github.ref }}-variation
  cancel-in-progress: true

jobs:
  websiteDockerImage:
    name: Build Website Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: dockerMetadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./website
          push: true
          tags: ${{ steps.dockerMetadata.outputs.tags }}
          labels: ${{ steps.dockerMetadata.outputs.labels }}

  updateDockerImages:
    runs-on: ubuntu-latest
    steps:
      - name: Update docker images
        uses: ./.github/workflows/reusable-workflow.yml@main
        with:
          ansible_file: 'provision/updateWebsite.yml'
