name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    container:
      image: mcr.microsoft.com/playwright:v1.36.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install dependencies
        run: npm ci
      - name: Serve the website
        run: npm run dev -- --port=3000 &
        env:
          CI: true
      - name: Run your tests
        run: npm run test:e2e