name: Provision Server

on: workflow_dispatch

jobs:
  provisionServer:
    runs-on: ubuntu-latest
    steps:
      - name: ProvisionServer
        uses: ./.github/workflows/ansibleOnServer.yml@main
        with:
          ansible_file: 'provision/provisionServer.yml'

  startContainers:
    runs-on: ubuntu-latest
    steps:
      - name: StartContainers
        uses: ./.github/workflows/ansibleOnServer.yml@main
        with:
          ansible_file: 'provision/startContainers.yml'
