name: Provision Server

on: workflow_dispatch

jobs:
  provisionServer:
    uses: ./.github/workflows/ansibleOnServer.yml
    with:
      ansible_file: 'server/provision/provisionServer.yml'
    secrets:
      SERVER_SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      SERVER_IP_ADDRESS: ${{ secrets.SERVER_IP_ADDRESS }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_USER_PASSWORD: ${{ secrets.SERVER_USER_PASSWORD }}
