name: Start Containers on Server

on: workflow_dispatch

jobs:
  provisionServer:
    runs-on: ubuntu-latest
    steps:
      - name: ProvisionServer
        uses: ./.github/workflows/reusable-workflow.yml@main
        with:
          ansible_file: 'provision/startContainers.yml'
